name: Manually trigger an Azure Machine Learning job

on:
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
        
    ### I completed this file with the following two steps
    # Step 4: Set the Azure subscription 
    - name: Set Azure subscription
      run: az account set --subscription b80dc029-950a-4131-83a0-9491479bf6bb

    # Step 5: Submit the Azure Machine Learning job 
    - name: Submit Azure ML job
      run: |
        az ml job create --resource-group fmianji-rg \
                         --workspace-name fmianji-ws \
                         --file ./src/job.yml

